import type { HskTestQuestion, HskTestQuestionBank } from "./types";

// ---------------------------------------------------------------------------
// HSK 1 — vocabulary, basic grammar, easy reading.
// ---------------------------------------------------------------------------
const HSK_1: HskTestQuestion[] = [
  {
    id: "hsk1_q01",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "你好",
    pinyin: "nǐ hǎo",
    question: "Что означает 你好?",
    options: ["Привет", "Спасибо", "До свидания", "Извините"],
    correct: 0,
  },
  {
    id: "hsk1_q02",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "谢谢",
    pinyin: "xièxie",
    question: "Что означает 谢谢?",
    options: ["Извините", "Спасибо", "Здравствуйте", "Пока"],
    correct: 1,
  },
  {
    id: "hsk1_q03",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "再见",
    pinyin: "zàijiàn",
    question: "Что означает 再见?",
    options: ["Привет", "Спокойной ночи", "До свидания", "Пожалуйста"],
    correct: 2,
  },
  {
    id: "hsk1_q04",
    level: 1,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "妈妈",
    question: "Выберите правильный пиньинь для 妈妈",
    options: ["māma", "māmá", "mǎmā", "mámá"],
    correct: 0,
  },
  {
    id: "hsk1_q05",
    level: 1,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "学生",
    question: "Выберите правильный пиньинь для 学生",
    options: ["xuésheng", "xiéshēng", "xuéshéng", "xiùshēng"],
    correct: 0,
  },
  {
    id: "hsk1_q06",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "老师",
    pinyin: "lǎoshī",
    question: "Что означает 老师?",
    options: ["Друг", "Студент", "Врач", "Учитель"],
    correct: 3,
  },
  {
    id: "hsk1_q07",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "我",
    pinyin: "wǒ",
    question: "Что означает 我?",
    options: ["я", "ты", "он", "она"],
    correct: 0,
  },
  {
    id: "hsk1_q08",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "水",
    pinyin: "shuǐ",
    question: "Что означает 水?",
    options: ["огонь", "вода", "земля", "чай"],
    correct: 1,
  },
  {
    id: "hsk1_q09",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "中国",
    pinyin: "Zhōngguó",
    question: "Что означает 中国?",
    options: ["Япония", "Корея", "Китай", "Тайвань"],
    correct: 2,
  },
  {
    id: "hsk1_q10",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "苹果",
    pinyin: "píngguǒ",
    question: "Что означает 苹果?",
    options: ["банан", "груша", "яблоко", "арбуз"],
    correct: 2,
  },
  {
    id: "hsk1_q11",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 学生。",
    pinyin: "Wǒ ___ xuésheng.",
    translation: "Я студент.",
    question: "Какое слово подходит в пропуск?",
    options: ["是", "有", "在", "不"],
    correct: 0,
  },
  {
    id: "hsk1_q12",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "你 ___ 妈妈?",
    pinyin: "Nǐ ___ māma?",
    translation: "Ты — мама? (вопрос с 吗)",
    question: "Какое слово сделает фразу вопросом «Ты — мама?»",
    options: ["了", "吗", "呢", "的"],
    correct: 1,
  },
  {
    id: "hsk1_q13",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 喜欢苹果。",
    pinyin: "Wǒ ___ xǐhuan píngguǒ.",
    translation: "Я не люблю яблоки.",
    question: "Какое слово делает предложение отрицательным?",
    options: ["很", "也", "不", "都"],
    correct: 2,
  },
  {
    id: "hsk1_q14",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我家有三 ___ 人。",
    pinyin: "Wǒ jiā yǒu sān ___ rén.",
    translation: "В моей семье три человека.",
    question: "Какое счётное слово нужно?",
    options: ["个", "本", "只", "杯"],
    correct: 0,
  },
  {
    id: "hsk1_q15",
    level: 1,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Я иду в школу.",
    tiles: ["我", "去", "学校"],
    correctOrder: [0, 1, 2],
  },
  {
    id: "hsk1_q16",
    level: 1,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Он любит пить чай.",
    tiles: ["喜欢", "他", "茶", "喝"],
    correctOrder: [1, 0, 3, 2],
  },
  {
    id: "hsk1_q17",
    level: 1,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите китайские слова и их перевод",
    left: ["书", "猫", "茶", "车"],
    right: ["книга", "кошка", "чай", "машина"],
  },
  {
    id: "hsk1_q18",
    level: 1,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите дни и их перевод",
    left: ["今天", "明天", "昨天", "星期一"],
    right: ["сегодня", "завтра", "вчера", "понедельник"],
  },
  {
    id: "hsk1_q19",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "吃饭",
    pinyin: "chī fàn",
    question: "Что означает 吃饭?",
    options: ["читать книгу", "пить воду", "есть (питаться)", "идти в школу"],
    correct: 2,
  },
  {
    id: "hsk1_q20",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "今天",
    pinyin: "jīntiān",
    question: "Что означает 今天?",
    options: ["завтра", "сегодня", "вчера", "позавчера"],
    correct: 1,
  },
  {
    id: "hsk1_q21",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "工作",
    pinyin: "gōngzuò",
    question: "Что означает 工作?",
    options: ["работа", "отдых", "учёба", "выходной"],
    correct: 0,
  },
  {
    id: "hsk1_q22",
    level: 1,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "电脑",
    question: "Выберите правильный пиньинь для 电脑",
    options: ["diànnǎo", "diànlào", "tiānnǎo", "diǎnnǎo"],
    correct: 0,
  },
  {
    id: "hsk1_q23",
    level: 1,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "朋友",
    question: "Выберите правильный пиньинь для 朋友",
    options: ["pénggyǒu", "péngyou", "pényou", "péngyóu"],
    correct: 1,
  },
  {
    id: "hsk1_q24",
    level: 1,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage: "我叫王明。我是学生。我有一个妹妹。",
    passagePinyin: "Wǒ jiào Wáng Míng. Wǒ shì xuésheng. Wǒ yǒu yí ge mèimei.",
    question: "Кто такой Ван Мин?",
    options: ["учитель", "врач", "студент", "повар"],
    correct: 2,
  },
  {
    id: "hsk1_q25",
    level: 1,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage: "今天星期六。我和爸爸去商店买苹果。",
    passagePinyin:
      "Jīntiān xīngqīliù. Wǒ hé bàba qù shāngdiàn mǎi píngguǒ.",
    question: "Что они идут покупать?",
    options: ["хлеб", "молоко", "яблоки", "чай"],
    correct: 2,
  },
  {
    id: "hsk1_q26",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "医院",
    pinyin: "yīyuàn",
    question: "Что означает 医院?",
    options: ["школа", "магазин", "больница", "ресторан"],
    correct: 2,
  },
  {
    id: "hsk1_q27",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "出租车",
    pinyin: "chūzūchē",
    question: "Что означает 出租车?",
    options: ["автобус", "поезд", "велосипед", "такси"],
    correct: 3,
  },
  {
    id: "hsk1_q28",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "现在 ___ 点?",
    pinyin: "Xiànzài ___ diǎn?",
    translation: "Который сейчас час?",
    question: "Какое слово подходит в пропуск?",
    options: ["什么", "几", "谁", "哪"],
    correct: 1,
  },
  {
    id: "hsk1_q29",
    level: 1,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Сегодня очень жарко.",
    tiles: ["热", "今天", "很"],
    correctOrder: [1, 2, 0],
  },
  {
    id: "hsk1_q30",
    level: 1,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите числа",
    left: ["一", "二", "三", "十"],
    right: ["один", "два", "три", "десять"],
  },
  {
    id: "hsk1_q31",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "下午",
    pinyin: "xiàwǔ",
    question: "Что означает 下午?",
    options: ["утро", "полдень", "после полудня", "вечер"],
    correct: 2,
  },
  {
    id: "hsk1_q32",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "前面",
    pinyin: "qiánmiàn",
    question: "Что означает 前面?",
    options: ["спереди", "сзади", "слева", "справа"],
    correct: 0,
  },
  {
    id: "hsk1_q33",
    level: 1,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "高兴",
    question: "Выберите правильный пиньинь для 高兴",
    options: ["gāoxìng", "gǎoxìng", "gāoxīn", "kāoxìng"],
    correct: 0,
  },
  {
    id: "hsk1_q34",
    level: 1,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "这 ___ 我的书。",
    pinyin: "Zhè ___ wǒ de shū.",
    translation: "Это моя книга.",
    question: "Какое слово подходит в пропуск?",
    options: ["有", "是", "在", "不"],
    correct: 1,
  },
  {
    id: "hsk1_q35",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "钱",
    pinyin: "qián",
    question: "Что означает 钱?",
    options: ["долг", "товар", "деньги", "стоимость"],
    correct: 2,
  },
  {
    id: "hsk1_q36",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "下雨",
    pinyin: "xià yǔ",
    question: "Что означает 下雨?",
    options: ["идёт снег", "идёт дождь", "светит солнце", "дует ветер"],
    correct: 1,
  },
  {
    id: "hsk1_q37",
    level: 1,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Я живу в Москве.",
    tiles: ["在", "莫斯科", "我", "住"],
    correctOrder: [2, 0, 1, 3],
  },
  {
    id: "hsk1_q38",
    level: 1,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage: "我每天八点去公司。中午我在公司吃饭。",
    passagePinyin:
      "Wǒ měi tiān bā diǎn qù gōngsī. Zhōngwǔ wǒ zài gōngsī chīfàn.",
    question: "Где этот человек обедает?",
    options: ["дома", "в ресторане", "в офисе", "в кафе"],
    correct: 2,
  },
  {
    id: "hsk1_q39",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "看",
    pinyin: "kàn",
    question: "Что означает 看?",
    options: ["слушать", "смотреть / читать", "писать", "говорить"],
    correct: 1,
  },
  {
    id: "hsk1_q40",
    level: 1,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "听",
    pinyin: "tīng",
    question: "Что означает 听?",
    options: ["смотреть", "слушать", "помнить", "понимать"],
    correct: 1,
  },
  // Audio HSK 1
  {
    id: "hsk1_q41",
    level: 1,
    type: "audio_choice",
    difficulty: 1.5,
    skill: "listening",
    audioText: "你好",
    question: "Что вы услышали?",
    options: ["Привет", "Спасибо", "До свидания", "Извините"],
    correct: 0,
  },
  {
    id: "hsk1_q42",
    level: 1,
    type: "audio_choice",
    difficulty: 1.5,
    skill: "listening",
    audioText: "我是学生",
    question: "Что означает эта фраза?",
    options: [
      "Я учитель",
      "Я студент",
      "Я китаец",
      "Я не понимаю",
    ],
    correct: 1,
  },
  {
    id: "hsk1_q43",
    level: 1,
    type: "tone_id",
    difficulty: 1.5,
    skill: "listening",
    audioText: "妈",
    syllable: "ma",
    correct: 1,
  },
  {
    id: "hsk1_q44",
    level: 1,
    type: "tone_id",
    difficulty: 1.5,
    skill: "listening",
    audioText: "马",
    syllable: "ma",
    correct: 3,
  },
  {
    id: "hsk1_q45",
    level: 1,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "明天我去北京",
    question: "Куда и когда едет говорящий?",
    options: [
      "Сегодня в Шанхай",
      "Завтра в Пекин",
      "Вчера в Пекин",
      "Завтра в Шанхай",
    ],
    correct: 1,
  },
];

// ---------------------------------------------------------------------------
// HSK 2 — daily life, 了-aspect, modal verbs, comparison.
// ---------------------------------------------------------------------------
const HSK_2: HskTestQuestion[] = [
  {
    id: "hsk2_q01",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "便宜",
    pinyin: "piányi",
    question: "Что означает 便宜?",
    options: ["дорогой", "дешёвый", "новый", "старый"],
    correct: 1,
  },
  {
    id: "hsk2_q02",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "火车",
    pinyin: "huǒchē",
    question: "Что означает 火车?",
    options: ["самолёт", "корабль", "поезд", "автобус"],
    correct: 2,
  },
  {
    id: "hsk2_q03",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "机场",
    pinyin: "jīchǎng",
    question: "Что означает 机场?",
    options: ["вокзал", "пристань", "аэропорт", "рынок"],
    correct: 2,
  },
  {
    id: "hsk2_q04",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "颜色",
    pinyin: "yánsè",
    question: "Что означает 颜色?",
    options: ["цвет", "форма", "размер", "вес"],
    correct: 0,
  },
  {
    id: "hsk2_q05",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "为什么",
    pinyin: "wèishénme",
    question: "Что означает 为什么?",
    options: ["когда", "почему", "сколько", "какой"],
    correct: 1,
  },
  {
    id: "hsk2_q06",
    level: 2,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "希望",
    question: "Выберите правильный пиньинь для 希望",
    options: ["xīwàng", "xíwàng", "xíwáng", "xìwàng"],
    correct: 0,
  },
  {
    id: "hsk2_q07",
    level: 2,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "已经",
    question: "Выберите правильный пиньинь для 已经",
    options: ["yìjǐng", "yǐjīng", "yīqǐng", "yìjīng"],
    correct: 1,
  },
  {
    id: "hsk2_q08",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我昨天吃 ___ 中国菜。",
    pinyin: "Wǒ zuótiān chī ___ zhōngguó cài.",
    translation: "Вчера я съел китайскую еду.",
    question: "Какая частица обозначает завершённость действия?",
    options: ["着", "过", "了", "的"],
    correct: 2,
  },
  {
    id: "hsk2_q09",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 说汉语。",
    pinyin: "Wǒ ___ shuō Hànyǔ.",
    translation: "Я умею говорить по-китайски.",
    question: "Какой модальный глагол передаёт «умение»?",
    options: ["想", "会", "应该", "可以"],
    correct: 1,
  },
  {
    id: "hsk2_q10",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "今天 ___ 昨天热。",
    pinyin: "Jīntiān ___ zuótiān rè.",
    translation: "Сегодня жарче, чем вчера.",
    question: "Какое слово вводит сравнение?",
    options: ["比", "和", "跟", "像"],
    correct: 0,
  },
  {
    id: "hsk2_q11",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 去过北京。",
    pinyin: "Wǒ ___ qùguo Běijīng.",
    translation: "Я никогда не был в Пекине.",
    question: "Какое слово передаёт «никогда»?",
    options: ["不", "没", "别", "无"],
    correct: 1,
  },
  {
    id: "hsk2_q12",
    level: 2,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Я хочу купить билет до Шанхая.",
    tiles: ["我", "想", "买", "去", "上海", "的", "票"],
    correctOrder: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "hsk2_q13",
    level: 2,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Завтра я не смогу прийти.",
    tiles: ["明天", "我", "来", "不能"],
    correctOrder: [0, 1, 3, 2],
  },
  {
    id: "hsk2_q14",
    level: 2,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Эта книга интереснее той.",
    tiles: ["这本书", "那本书", "有意思", "比"],
    correctOrder: [0, 3, 1, 2],
  },
  {
    id: "hsk2_q15",
    level: 2,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова и перевод",
    left: ["问题", "时候", "事情", "意思"],
    right: ["вопрос / проблема", "момент / время", "дело", "смысл"],
  },
  {
    id: "hsk2_q16",
    level: 2,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите глаголы и перевод",
    left: ["介绍", "认识", "开始", "完成"],
    right: ["представлять", "быть знакомым", "начинать", "завершать"],
  },
  {
    id: "hsk2_q17",
    level: 2,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我喜欢中国菜，因为它很有意思。我朋友每个星期都教我做菜。下个月我要去她家学做饺子。",
    question: "Что собирается делать рассказчик в следующем месяце?",
    options: [
      "поехать в Китай",
      "научиться лепить пельмени дома у подруги",
      "открыть ресторан",
      "пойти на курсы кулинарии",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q18",
    level: 2,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我家离学校不远，骑自行车十分钟就能到。但是今天下雨，所以我坐了出租车。",
    question: "Почему рассказчик сегодня поехал на такси?",
    options: [
      "велосипед сломался",
      "уроки начались раньше",
      "идёт дождь",
      "школа далеко"
    ],
    correct: 2,
  },
  {
    id: "hsk2_q19",
    level: 2,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение построено правильно?",
    options: [
      "我去了北京昨天。",
      "昨天我去了北京。",
      "我昨天北京去了。",
      "昨天北京我去了。",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q20",
    level: 2,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Выберите правильный вариант со словом 比",
    options: [
      "我很高比他。",
      "我高比他很。",
      "我比他高。",
      "我比他很高。",
    ],
    correct: 2,
  },
  {
    id: "hsk2_q21",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "公司",
    pinyin: "gōngsī",
    question: "Что означает 公司?",
    options: ["школа", "магазин", "офис", "компания / фирма"],
    correct: 3,
  },
  {
    id: "hsk2_q22",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "右边",
    pinyin: "yòubian",
    question: "Что означает 右边?",
    options: ["слева", "справа", "сверху", "снизу"],
    correct: 1,
  },
  {
    id: "hsk2_q23",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "他 ___ 喜欢喝咖啡。",
    pinyin: "Tā ___ xǐhuan hē kāfēi.",
    translation: "Он очень любит пить кофе.",
    question: "Какое наречие подходит?",
    options: ["非常", "再", "就", "都"],
    correct: 0,
  },
  {
    id: "hsk2_q24",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "你能 ___ 我打电话吗?",
    pinyin: "Nǐ néng ___ wǒ dǎ diànhuà ma?",
    translation: "Можешь позвонить мне?",
    question: "Какой предлог нужен?",
    options: ["在", "给", "用", "对"],
    correct: 1,
  },
  {
    id: "hsk2_q25",
    level: 2,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Он играет в футбол лучше меня.",
    tiles: ["他", "我", "好", "比", "踢足球"],
    correctOrder: [0, 4, 3, 1, 2],
  },
  {
    id: "hsk2_q26",
    level: 2,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова о погоде",
    left: ["晴天", "阴天", "下雪", "刮风"],
    right: ["ясно", "облачно", "идёт снег", "ветер"],
  },
  {
    id: "hsk2_q27",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "锻炼",
    pinyin: "duànliàn",
    question: "Что означает 锻炼?",
    options: ["отдыхать", "тренироваться", "учиться", "плакать"],
    correct: 1,
  },
  {
    id: "hsk2_q28",
    level: 2,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "上个星期，我和家人去了公园。我们在那里看到了很多花和小猫。儿子说他下次还想去。",
    question: "Что увидели в парке?",
    options: ["птиц и собак", "цветы и кошек", "лошадей", "только людей"],
    correct: 1,
  },
  {
    id: "hsk2_q29",
    level: 2,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Выберите правильное предложение с 了",
    options: [
      "我吃饭了。",
      "我了吃饭。",
      "我饭吃了。",
      "了我吃饭。",
    ],
    correct: 0,
  },
  {
    id: "hsk2_q30",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "旁边",
    pinyin: "pángbiān",
    question: "Что означает 旁边?",
    options: ["рядом", "напротив", "позади", "среди"],
    correct: 0,
  },
  {
    id: "hsk2_q31",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我们一起 ___ 看电影吧!",
    pinyin: "Wǒmen yìqǐ ___ kàn diànyǐng ba!",
    translation: "Пойдём вместе посмотрим фильм!",
    question: "Какой глагол подходит?",
    options: ["去", "来", "走", "回"],
    correct: 0,
  },
  {
    id: "hsk2_q32",
    level: 2,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "聪明",
    question: "Выберите правильный пиньинь для 聪明",
    options: ["cōngmín", "cōngming", "chōngmíng", "sōngmíng"],
    correct: 1,
  },
  {
    id: "hsk2_q33",
    level: 2,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Эта одежда мне немного велика.",
    tiles: ["这件衣服", "大", "我", "对", "有点儿"],
    correctOrder: [0, 3, 2, 4, 1],
  },
  {
    id: "hsk2_q34",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "穿",
    pinyin: "chuān",
    question: "Что означает глагол 穿?",
    options: ["снимать", "надевать (одежду)", "стирать", "сушить"],
    correct: 1,
  },
  {
    id: "hsk2_q35",
    level: 2,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите время и перевод",
    left: ["以前", "以后", "正在", "马上"],
    right: ["до / раньше", "после", "прямо сейчас", "сразу"],
  },
  {
    id: "hsk2_q36",
    level: 2,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение со словом 在 правильное?",
    options: [
      "我在打电话现在。",
      "我现在在打电话。",
      "我现在打电话在。",
      "在我现在打电话。",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q37",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "考试",
    pinyin: "kǎoshì",
    question: "Что означает 考试?",
    options: ["перемена", "экзамен", "оценка", "урок"],
    correct: 1,
  },
  {
    id: "hsk2_q38",
    level: 2,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "完",
    pinyin: "wán",
    question: "Что означает 完 в составе глагола?",
    options: [
      "начинать",
      "пробовать",
      "закончить (результат)",
      "продолжать",
    ],
    correct: 2,
  },
  {
    id: "hsk2_q39",
    level: 2,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 去过中国两次。",
    pinyin: "Wǒ ___ qùguo Zhōngguó liǎng cì.",
    translation: "Я уже два раза был в Китае.",
    question: "Какое наречие подходит?",
    options: ["还", "再", "已经", "就"],
    correct: 2,
  },
  {
    id: "hsk2_q40",
    level: 2,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我妹妹今年十岁。她喜欢唱歌，但是不喜欢跳舞。她说以后想当老师。",
    question: "Кем хочет стать сестра?",
    options: ["певицей", "танцовщицей", "врачом", "учительницей"],
    correct: 3,
  },
  // Audio HSK 2
  {
    id: "hsk2_q41",
    level: 2,
    type: "audio_choice",
    difficulty: 1.5,
    skill: "listening",
    audioText: "今天天气很好",
    question: "О чём говорит фраза?",
    options: [
      "Сегодня плохая погода",
      "Сегодня очень хорошая погода",
      "Завтра будет дождь",
      "Вчера было жарко",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q42",
    level: 2,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "我想买一张去北京的火车票",
    question: "Что хочет купить говорящий?",
    options: [
      "билет на самолёт в Пекин",
      "билет на поезд в Пекин",
      "билет в Шанхай",
      "билет на автобус",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q43",
    level: 2,
    type: "audio_choice",
    difficulty: 1.5,
    skill: "listening",
    audioText: "这件衣服多少钱",
    question: "О чём спрашивает говорящий?",
    options: [
      "Где купить одежду",
      "Сколько стоит эта одежда",
      "Какой цвет одежды",
      "Какой размер",
    ],
    correct: 1,
  },
  {
    id: "hsk2_q44",
    level: 2,
    type: "tone_id",
    difficulty: 1.5,
    skill: "listening",
    audioText: "妹",
    syllable: "mei",
    correct: 4,
  },
  {
    id: "hsk2_q45",
    level: 2,
    type: "tone_id",
    difficulty: 1.5,
    skill: "listening",
    audioText: "买",
    syllable: "mai",
    correct: 3,
  },
];

// ---------------------------------------------------------------------------
// HSK 3 — 把-construction, conditional, longer reading.
// ---------------------------------------------------------------------------
const HSK_3: HskTestQuestion[] = [
  {
    id: "hsk3_q01",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "习惯",
    pinyin: "xíguàn",
    question: "Что означает 习惯?",
    options: ["правило", "привычка", "способ", "выбор"],
    correct: 1,
  },
  {
    id: "hsk3_q02",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "经验",
    pinyin: "jīngyàn",
    question: "Что означает 经验?",
    options: ["опыт", "образование", "знание", "наука"],
    correct: 0,
  },
  {
    id: "hsk3_q03",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "举行",
    pinyin: "jǔxíng",
    question: "Что означает 举行?",
    options: ["открывать", "проводить (мероприятие)", "выбирать", "решать"],
    correct: 1,
  },
  {
    id: "hsk3_q04",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "影响",
    pinyin: "yǐngxiǎng",
    question: "Что означает 影响?",
    options: ["удивление", "влияние", "звук", "сила"],
    correct: 1,
  },
  {
    id: "hsk3_q05",
    level: 3,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "环境",
    question: "Выберите правильный пиньинь для 环境",
    options: ["huánjìng", "huánjǐng", "hánjìng", "huānjìng"],
    correct: 0,
  },
  {
    id: "hsk3_q06",
    level: 3,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "解决",
    question: "Выберите правильный пиньинь для 解决",
    options: ["jiějué", "jiějuě", "xièjué", "jièjuè"],
    correct: 0,
  },
  {
    id: "hsk3_q07",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我已经 ___ 作业写完了。",
    pinyin: "Wǒ yǐjīng ___ zuòyè xiě wán le.",
    translation: "Я уже закончил писать домашнее задание.",
    question: "Какой служебный элемент нужен?",
    options: ["把", "被", "对", "比"],
    correct: 0,
  },
  {
    id: "hsk3_q08",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "___ 你早点儿来，我们就能多聊一会儿。",
    pinyin: "___ nǐ zǎodiǎnr lái, wǒmen jiù néng duō liáo yíhuìr.",
    translation: "Если ты придёшь пораньше, мы сможем больше пообщаться.",
    question: "Какое слово начинает условную фразу?",
    options: ["虽然", "如果", "因为", "不但"],
    correct: 1,
  },
  {
    id: "hsk3_q09",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "他一边听音乐，___ 做饭。",
    pinyin: "Tā yìbiān tīng yīnyuè, ___ zuòfàn.",
    translation: "Он одновременно слушает музыку и готовит.",
    question: "Что подходит во вторую часть конструкции?",
    options: ["一边", "一会儿", "一下", "一直"],
    correct: 0,
  },
  {
    id: "hsk3_q10",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "对不起，我 ___ 听清楚你说的话。",
    pinyin: "Duìbuqǐ, wǒ ___ tīng qīngchu nǐ shuō de huà.",
    translation: "Извини, я не расслышал, что ты сказал.",
    question: "Какое слово отрицает результат?",
    options: ["不", "没", "别", "不要"],
    correct: 1,
  },
  {
    id: "hsk3_q11",
    level: 3,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Пожалуйста, закройте окно.",
    tiles: ["请", "把", "关上", "窗户"],
    correctOrder: [0, 1, 3, 2],
  },
  {
    id: "hsk3_q12",
    level: 3,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Чем больше я думаю, тем больше волнуюсь.",
    tiles: ["越", "越", "我", "想", "担心"],
    correctOrder: [2, 0, 3, 1, 4],
  },
  {
    id: "hsk3_q13",
    level: 3,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Хотя сегодня устал, я всё ещё хочу позаниматься.",
    tiles: ["虽然", "今天", "很累", "我", "但是", "想学习", "还"],
    correctOrder: [0, 1, 3, 2, 4, 3, 6],
  },
  {
    id: "hsk3_q14",
    level: 3,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Выберите правильное предложение с 把",
    options: [
      "我把书放在了桌子上。",
      "我把放书桌子上了在。",
      "我书把放在桌子上了。",
      "把我书放桌子上在了。",
    ],
    correct: 0,
  },
  {
    id: "hsk3_q15",
    level: 3,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение со словом 让 правильное?",
    options: [
      "妈妈让弟弟去买东西。",
      "妈妈让去买弟弟东西。",
      "让妈妈弟弟去买东西。",
      "妈妈弟弟让东西去买。",
    ],
    correct: 0,
  },
  {
    id: "hsk3_q16",
    level: 3,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "上个月我开始学骑自行车。一开始我总是摔倒，后来我朋友每天陪我练习。现在我已经能骑得很好了，周末还能和朋友们一起去公园。",
    question: "Как герой научился ездить на велосипеде?",
    options: [
      "ходил на специальные курсы",
      "учился по видео в интернете",
      "практиковался с другом, который помогал",
      "научил младший брат",
    ],
    correct: 2,
  },
  {
    id: "hsk3_q17",
    level: 3,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我打算这个暑假去南方旅行。我已经买了去上海的机票，还订了酒店。但我朋友说，南方夏天又热又湿，让我多带几件薄衣服和雨伞。",
    question: "Что советует друг?",
    options: [
      "взять много тёплой одежды",
      "взять тонкие вещи и зонт",
      "отменить поездку",
      "ехать не летом, а зимой",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q18",
    level: 3,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите союзы и их значение",
    left: ["因为", "所以", "虽然", "但是"],
    right: ["потому что", "поэтому", "хотя", "но / однако"],
  },
  {
    id: "hsk3_q19",
    level: 3,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите глаголы и перевод",
    left: ["复习", "练习", "提高", "选择"],
    right: ["повторять", "тренироваться", "повышать", "выбирать"],
  },
  {
    id: "hsk3_q20",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "差不多",
    pinyin: "chàbuduō",
    question: "Что означает 差不多?",
    options: [
      "сильно отличается",
      "примерно / почти то же самое",
      "никогда не получается",
      "медленно",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q21",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "建议",
    pinyin: "jiànyì",
    question: "Что означает 建议?",
    options: ["знание", "совет / рекомендация", "решение", "вопрос"],
    correct: 1,
  },
  {
    id: "hsk3_q22",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "你 ___ 去过几次中国?",
    pinyin: "Nǐ ___ qùguo jǐ cì Zhōngguó?",
    translation: "Сколько раз ты уже был в Китае?",
    question: "Какое наречие подходит?",
    options: ["还", "总共", "永远", "突然"],
    correct: 1,
  },
  {
    id: "hsk3_q23",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我 ___ 学习汉语 ___ 喜欢中国文化。",
    pinyin: "Wǒ ___ xuéxí Hànyǔ ___ xǐhuan Zhōngguó wénhuà.",
    translation: "Я не только учу китайский, но и люблю китайскую культуру.",
    question: "Какая пара союзов подходит?",
    options: [
      "因为...所以...",
      "不但...而且...",
      "虽然...但是...",
      "如果...就...",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q24",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "刚才",
    pinyin: "gāngcái",
    question: "Что означает 刚才?",
    options: ["скоро", "только что", "недавно", "позже"],
    correct: 1,
  },
  {
    id: "hsk3_q25",
    level: 3,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Учитель попросил меня объяснить этот вопрос.",
    tiles: ["老师", "让", "我", "解释", "这个", "问题"],
    correctOrder: [0, 1, 2, 3, 4, 5],
  },
  {
    id: "hsk3_q26",
    level: 3,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение с 被 правильное?",
    options: [
      "我的手机被弟弟摔坏了。",
      "我的手机被摔坏弟弟了。",
      "被我的手机弟弟摔坏了。",
      "弟弟摔坏被手机了。",
    ],
    correct: 0,
  },
  {
    id: "hsk3_q27",
    level: 3,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我家附近开了一家新咖啡馆。环境很安静，咖啡也不贵。每天早上很多人在那里看书、写东西。我也常常去那里复习中文。",
    question: "Зачем рассказчик ходит в это кафе?",
    options: [
      "встречаться с коллегами",
      "обедать",
      "повторять китайский",
      "продавать кофе",
    ],
    correct: 2,
  },
  {
    id: "hsk3_q28",
    level: 3,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "其实",
    question: "Выберите правильный пиньинь для 其实",
    options: ["qíshí", "qǐshī", "qíshì", "jīshí"],
    correct: 0,
  },
  {
    id: "hsk3_q29",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "其实",
    pinyin: "qíshí",
    question: "Что означает 其实?",
    options: ["просто", "по-настоящему / на самом деле", "вначале", "обычно"],
    correct: 1,
  },
  {
    id: "hsk3_q30",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "他汉语说 ___ 很流利。",
    pinyin: "Tā Hànyǔ shuō ___ hěn liúlì.",
    translation: "Он говорит по-китайски очень бегло.",
    question: "Какой служебный элемент подходит?",
    options: ["得", "的", "地", "了"],
    correct: 0,
  },
  {
    id: "hsk3_q31",
    level: 3,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова с временем",
    left: ["将来", "过去", "现在", "马上"],
    right: ["будущее", "прошлое", "настоящее", "вот-вот"],
  },
  {
    id: "hsk3_q32",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "了解",
    pinyin: "liǎojiě",
    question: "Что означает 了解?",
    options: ["знакомиться", "понимать / разбираться", "забывать", "узнавать"],
    correct: 1,
  },
  {
    id: "hsk3_q33",
    level: 3,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "小李最近换了工作。新公司离家比较远，每天要坐一个多小时的地铁。但是工资比以前高，工作内容也更有意思，所以他觉得很值得。",
    question: "Почему Сяо Ли доволен новой работой?",
    options: [
      "офис ближе к дому",
      "коллеги интереснее",
      "зарплата выше и работа интереснее",
      "может работать из дома",
    ],
    correct: 2,
  },
  {
    id: "hsk3_q34",
    level: 3,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Выберите правильное предложение",
    options: [
      "我打算明天去看朋友。",
      "我明天打算去看朋友。",
      "明天我去看朋友打算。",
      "我去看朋友打算明天。",
    ],
    correct: 0,
  },
  {
    id: "hsk3_q35",
    level: 3,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "她笑 ___ 说: «没关系»。",
    pinyin: "Tā xiào ___ shuō: «méi guānxi».",
    translation: "Она с улыбкой сказала: «ничего страшного».",
    question: "Что подходит после глагола?",
    options: ["着", "了", "过", "得"],
    correct: 0,
  },
  {
    id: "hsk3_q36",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "比较",
    pinyin: "bǐjiào",
    question: "Что означает 比较?",
    options: ["разделять", "сравнительно / относительно", "помогать", "тратить"],
    correct: 1,
  },
  {
    id: "hsk3_q37",
    level: 3,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Я переехал из Москвы в Пекин два года назад.",
    tiles: ["我", "两年前", "从", "莫斯科", "搬到", "北京"],
    correctOrder: [0, 1, 2, 3, 4, 5],
  },
  {
    id: "hsk3_q38",
    level: 3,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "其他",
    pinyin: "qítā",
    question: "Что означает 其他?",
    options: ["похожий", "иной / другой", "обычный", "следующий"],
    correct: 1,
  },
  {
    id: "hsk3_q39",
    level: 3,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите выражения и перевод",
    left: ["对了", "没关系", "不客气", "不好意思"],
    right: ["кстати", "ничего страшного", "пожалуйста (на спасибо)", "неловко / извините"],
  },
  {
    id: "hsk3_q40",
    level: 3,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "学校的图书馆周一到周六开门，周日休息。学生可以借五本书，借期两个星期。如果想再多借几天，可以打电话延长。",
    question: "Что нужно сделать, чтобы продлить срок?",
    options: [
      "вернуть книги и взять заново",
      "написать заявление",
      "позвонить в библиотеку",
      "оплатить штраф",
    ],
    correct: 2,
  },
  // Audio HSK 3
  {
    id: "hsk3_q41",
    level: 3,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "如果明天下雨，我们就在家复习中文",
    question: "При каком условии останутся дома?",
    options: [
      "если будет жарко",
      "если будет дождь",
      "если придут гости",
      "если устанут",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q42",
    level: 3,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "他一边听音乐，一边做饭",
    question: "Что он делает одновременно?",
    options: [
      "слушает музыку и готовит",
      "читает книгу и ест",
      "поёт и убирает",
      "смотрит фильм и работает",
    ],
    correct: 0,
  },
  {
    id: "hsk3_q43",
    level: 3,
    type: "audio_choice",
    difficulty: 1.5,
    skill: "listening",
    audioText: "我把作业写完了",
    question: "Что говорящий сделал с домашним заданием?",
    options: [
      "забыл его",
      "уже закончил его",
      "только начал",
      "потерял его",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q44",
    level: 3,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "请把窗户关上",
    question: "О чём просит говорящий?",
    options: [
      "открыть дверь",
      "закрыть окно",
      "включить свет",
      "выключить кондиционер",
    ],
    correct: 1,
  },
  {
    id: "hsk3_q45",
    level: 3,
    type: "tone_id",
    difficulty: 1.5,
    skill: "listening",
    audioText: "请",
    syllable: "qing",
    correct: 3,
  },
];

// ---------------------------------------------------------------------------
// HSK 4 — abstract topics, complex grammar, denser reading.
// ---------------------------------------------------------------------------
const HSK_4: HskTestQuestion[] = [
  {
    id: "hsk4_q01",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "效率",
    pinyin: "xiàolǜ",
    question: "Что означает 效率?",
    options: ["качество", "эффективность", "скорость", "результат"],
    correct: 1,
  },
  {
    id: "hsk4_q02",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "竞争",
    pinyin: "jìngzhēng",
    question: "Что означает 竞争?",
    options: ["сотрудничество", "соревнование / конкуренция", "выбор", "обмен"],
    correct: 1,
  },
  {
    id: "hsk4_q03",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "趋势",
    pinyin: "qūshì",
    question: "Что означает 趋势?",
    options: ["причина", "тенденция / тренд", "интерес", "правило"],
    correct: 1,
  },
  {
    id: "hsk4_q04",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "适应",
    pinyin: "shìyìng",
    question: "Что означает 适应?",
    options: ["приспосабливаться", "выбирать", "согласиться", "разрешать"],
    correct: 0,
  },
  {
    id: "hsk4_q05",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "态度",
    pinyin: "tàidu",
    question: "Что означает 态度?",
    options: ["цель", "взгляд", "отношение / позиция", "характер"],
    correct: 2,
  },
  {
    id: "hsk4_q06",
    level: 4,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "鼓励",
    question: "Выберите правильный пиньинь для 鼓励",
    options: ["gǔlì", "gùlì", "kǔlì", "gǔlǐ"],
    correct: 0,
  },
  {
    id: "hsk4_q07",
    level: 4,
    type: "pinyin",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "确定",
    question: "Выберите правильный пиньинь для 确定",
    options: ["quèdìng", "qùedìng", "qiàodìng", "quédǐng"],
    correct: 0,
  },
  {
    id: "hsk4_q08",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "___ 工作很忙，___ 他每天都坚持锻炼。",
    pinyin: "___ gōngzuò hěn máng, ___ tā měi tiān dōu jiānchí duànliàn.",
    translation: "Хотя работа очень загружена, он каждый день тренируется.",
    question: "Какая пара союзов подходит?",
    options: [
      "因为...所以...",
      "虽然...但是...",
      "不仅...而且...",
      "只要...就...",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q09",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "___ 你每天练习，口语 ___ 会进步。",
    pinyin: "___ nǐ měi tiān liànxí, kǒuyǔ ___ huì jìnbù.",
    translation: "Если ты будешь заниматься каждый день, твоя устная речь обязательно улучшится.",
    question: "Какая пара союзов подходит?",
    options: [
      "如果...就...",
      "只要...就...",
      "虽然...还是...",
      "无论...都...",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q10",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "这次比赛 ___ 我学到了很多。",
    pinyin: "Zhè cì bǐsài ___ wǒ xuédào le hěn duō.",
    translation: "Это соревнование позволило мне многому научиться.",
    question: "Какой служебный элемент подходит?",
    options: ["把", "让", "被", "对"],
    correct: 1,
  },
  {
    id: "hsk4_q11",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我们公司 ___ 中国出口产品。",
    pinyin: "Wǒmen gōngsī ___ Zhōngguó chūkǒu chǎnpǐn.",
    translation: "Наша компания экспортирует товары в Китай.",
    question: "Какой предлог подходит?",
    options: ["从", "向", "为", "对"],
    correct: 1,
  },
  {
    id: "hsk4_q12",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "我已经把所有材料 ___ 给你了。",
    pinyin: "Wǒ yǐjīng bǎ suǒyǒu cáiliào ___ gěi nǐ le.",
    translation: "Я уже передал тебе все материалы.",
    question: "Какой результативный глагол подходит?",
    options: ["寄", "拿", "交", "送"],
    correct: 2,
  },
  {
    id: "hsk4_q13",
    level: 4,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "В последнее время погода меняется довольно резко.",
    tiles: ["最近", "天气", "比较", "变化", "大"],
    correctOrder: [0, 1, 3, 2, 4],
  },
  {
    id: "hsk4_q14",
    level: 4,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Хотя путь долгий, но я ни о чём не жалею.",
    tiles: ["虽然", "路", "很远", "但是", "我", "不", "后悔"],
    correctOrder: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: "hsk4_q15",
    level: 4,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение со словом 不仅 правильное?",
    options: [
      "他不仅会唱歌，而且会跳舞。",
      "他会唱歌不仅而且跳舞。",
      "他唱歌不仅，跳舞而且。",
      "不仅他会唱歌而且跳舞。",
    ],
    correct: 0,
  },
  {
    id: "hsk4_q16",
    level: 4,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Выберите правильное предложение с пассивом",
    options: [
      "我的钱包被人偷了。",
      "我的钱包人偷被了。",
      "被我的钱包人偷了。",
      "钱包我被人偷了的。",
    ],
    correct: 0,
  },
  {
    id: "hsk4_q17",
    level: 4,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение со словом 为了 построено правильно?",
    options: [
      "为了提高效率，我们要重新安排工作。",
      "为了我们要提高效率重新安排工作。",
      "我们要为了重新安排工作提高效率。",
      "提高效率为了，重新安排我们工作。",
    ],
    correct: 0,
  },
  {
    id: "hsk4_q18",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "随着网络的发展，越来越多的人喜欢在网上购物。网购方便、便宜，可以足不出户买到全世界的东西。不过，专家提醒大家，购物时一定要注意网站的信誉，不要在不熟悉的网站上输入银行卡信息。",
    question: "О чём предупреждает эксперт?",
    options: [
      "что цены в интернете выше",
      "что нужно проверять репутацию сайта и не вводить данные карты где попало",
      "что онлайн-покупки скоро запретят",
      "что доставка занимает много времени",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q19",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "很多人觉得学外语最难的是听力。其实，如果每天花二十分钟听原版材料，几个月后就会有明显进步。重要的不是听懂每一个词，而是抓住整段话的意思。",
    question: "Какой главный совет даёт автор?",
    options: [
      "учить каждый незнакомый иероглиф",
      "слушать только адаптированные материалы",
      "не пытаться понять каждое слово, а ловить общий смысл",
      "слушать только перед сном",
    ],
    correct: 2,
  },
  {
    id: "hsk4_q20",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "公司决定从下个月开始实行新的工作制度: 员工可以每周在家工作两天。这样的安排不仅能让大家更好地平衡工作和生活，也有助于提高工作效率。但同时，公司要求大家保证完成任务的质量。",
    question: "В чём суть нового режима?",
    options: [
      "полностью перевести всех на удалёнку",
      "разрешить работать из дома два дня в неделю при сохранении качества",
      "сократить рабочий день до 5 часов",
      "перенести офис в другой город",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q21",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "造成",
    pinyin: "zàochéng",
    question: "Что означает 造成?",
    options: [
      "создавать (вызывать что-то нежелательное)",
      "превращать",
      "проверять",
      "переводить",
    ],
    correct: 0,
  },
  {
    id: "hsk4_q22",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "丰富",
    pinyin: "fēngfù",
    question: "Что означает 丰富?",
    options: ["богатый / разнообразный", "тяжёлый", "сухой", "простой"],
    correct: 0,
  },
  {
    id: "hsk4_q23",
    level: 4,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова и перевод",
    left: ["发展", "实现", "提供", "保护"],
    right: ["развивать", "осуществлять", "предоставлять", "защищать"],
  },
  {
    id: "hsk4_q24",
    level: 4,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова и перевод",
    left: ["原因", "结果", "目的", "过程"],
    right: ["причина", "результат", "цель", "процесс"],
  },
  {
    id: "hsk4_q25",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "随便",
    pinyin: "suíbiàn",
    question: "Что означает 随便?",
    options: ["обязательно", "очень редко", "как угодно / на ваш вкус", "впервые"],
    correct: 2,
  },
  {
    id: "hsk4_q26",
    level: 4,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Этот проект во многом зависит от поддержки руководства.",
    tiles: [
      "这个项目",
      "在很大程度上",
      "取决于",
      "领导",
      "的",
      "支持",
    ],
    correctOrder: [0, 1, 2, 3, 4, 5],
  },
  {
    id: "hsk4_q27",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "经过 ___ 的努力，我们终于完成了任务。",
    pinyin: "Jīngguò ___ de nǔlì, wǒmen zhōngyú wánchéng le rènwù.",
    translation: "Благодаря многолетним усилиям мы наконец выполнили задачу.",
    question: "Какое словосочетание подходит?",
    options: ["几天", "多年", "一次", "短期"],
    correct: 1,
  },
  {
    id: "hsk4_q28",
    level: 4,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение со словом 越...越... правильное?",
    options: [
      "他汉语越说越好。",
      "他越汉语说好越。",
      "越他说汉语好越。",
      "他汉语好越越说。",
    ],
    correct: 0,
  },
  {
    id: "hsk4_q29",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "影响",
    pinyin: "yǐngxiǎng",
    question: "В каком значении 影响 чаще всего используется в HSK 4?",
    options: ["звук", "тень", "влияние / воздействие", "образ"],
    correct: 2,
  },
  {
    id: "hsk4_q30",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "我和小李是大学同学。毕业后我们去了不同的城市工作。这些年虽然见面少了，但每次聊天都觉得彼此一点都没变。真正的朋友不需要天天联系，重要的是心里一直留着对方的位置。",
    question: "Какова главная мысль текста?",
    options: [
      "друзья нужны только в трудные моменты",
      "важно постоянно общаться, иначе теряешь связь",
      "настоящие друзья остаются близкими даже без частых встреч",
      "после университета сложно сохранить дружбу",
    ],
    correct: 2,
  },
  {
    id: "hsk4_q31",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "无论遇到什么困难，他 ___ 不放弃。",
    pinyin: "Wúlùn yùdào shénme kùnnan, tā ___ bù fàngqì.",
    translation: "Какие бы трудности ни встретились, он никогда не сдаётся.",
    question: "Какое наречие подходит?",
    options: ["都", "再", "又", "也"],
    correct: 0,
  },
  {
    id: "hsk4_q32",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "积极",
    pinyin: "jījí",
    question: "Что означает 积极?",
    options: ["пассивный", "уверенный", "активный / положительный", "скромный"],
    correct: 2,
  },
  {
    id: "hsk4_q33",
    level: 4,
    type: "pair_matching",
    difficulty: 1.5,
    skill: "vocabulary",
    question: "Соотнесите слова и перевод",
    left: ["质量", "数量", "价格", "价值"],
    right: ["качество", "количество", "цена", "ценность / стоимость"],
  },
  {
    id: "hsk4_q34",
    level: 4,
    type: "grammar_choice",
    difficulty: 2.0,
    skill: "grammar",
    question: "Какое предложение построено правильно?",
    options: [
      "我把这本书已经看完了。",
      "我已经把这本书看完了。",
      "已经我把这本书看完了。",
      "我看完已经把这本书了。",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q35",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "现代社会节奏很快，人们常常感到压力大。专家建议每天给自己留一点儿时间，做喜欢的事情，比如听音乐、散步或读书。这样不仅能放松身心，还能提高第二天的工作效率。",
    question: "Что советуют специалисты?",
    options: [
      "больше работать вечером",
      "каждый день оставлять время на любимое занятие",
      "сменить работу",
      "отказаться от выходных",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q36",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "推广",
    pinyin: "tuīguǎng",
    question: "Что означает 推广?",
    options: ["переводить", "продвигать / распространять", "сравнивать", "понимать"],
    correct: 1,
  },
  {
    id: "hsk4_q37",
    level: 4,
    type: "sentence_order",
    difficulty: 1.5,
    skill: "grammar",
    translation: "Если бы я знал заранее, я бы взял зонт.",
    tiles: [
      "如果",
      "我",
      "提前",
      "知道",
      "我",
      "会",
      "带",
      "雨伞",
    ],
    correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    id: "hsk4_q38",
    level: 4,
    type: "fill_blank",
    difficulty: 1.5,
    skill: "grammar",
    sentence: "这件事 ___ 我们都有责任。",
    pinyin: "Zhè jiàn shì ___ wǒmen dōu yǒu zérèn.",
    translation: "За это дело все мы несём ответственность.",
    question: "Какой служебный элемент подходит?",
    options: ["对", "把", "向", "被"],
    correct: 0,
  },
  {
    id: "hsk4_q39",
    level: 4,
    type: "match_translation",
    difficulty: 1.0,
    skill: "vocabulary",
    prompt: "保证",
    pinyin: "bǎozhèng",
    question: "Что означает 保证?",
    options: ["гарантировать / обещать", "сохранять", "защищать", "проверять"],
    correct: 0,
  },
  {
    id: "hsk4_q40",
    level: 4,
    type: "reading",
    difficulty: 2.0,
    skill: "reading",
    passage:
      "中国的高铁近年来发展非常快。如今从北京到上海只需要四个多小时，比以前快了很多。高铁不仅节省时间，还方便又舒适，因此成为大多数人出差和旅游的首选。",
    question: "Почему скоростной поезд стал популярным выбором?",
    options: [
      "потому что он самый дешёвый вид транспорта",
      "потому что он быстрый, удобный и комфортный",
      "потому что других видов транспорта нет",
      "потому что государство платит за билеты",
    ],
    correct: 1,
  },
  // Audio HSK 4
  {
    id: "hsk4_q41",
    level: 4,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "随着经济的发展，越来越多的企业开始重视中文人才",
    question: "О чём говорит фраза?",
    options: [
      "Экономика падает, и компании сокращают людей",
      "С развитием экономики компании всё больше ценят специалистов со знанием китайского",
      "Молодёжь не хочет учить китайский",
      "Государство не помогает изучать языки",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q42",
    level: 4,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "虽然这个办法比较麻烦，但是效果很好",
    question: "Какова оценка способа?",
    options: [
      "Простой, но бесполезный",
      "Хлопотный, но эффективный",
      "И простой, и эффективный",
      "Сложный и бесполезный",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q43",
    level: 4,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "只要你每天练习，口语一定会提高",
    question: "Что нужно делать, чтобы устная речь улучшилась?",
    options: [
      "записаться на курсы",
      "тренироваться каждый день",
      "переехать в Китай",
      "слушать радио",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q44",
    level: 4,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "这次会议主要讨论公司明年的发展计划",
    question: "Что обсуждается на совещании?",
    options: [
      "финансовый отчёт",
      "план развития компании на следующий год",
      "найм сотрудников",
      "переезд офиса",
    ],
    correct: 1,
  },
  {
    id: "hsk4_q45",
    level: 4,
    type: "audio_choice",
    difficulty: 2.0,
    skill: "listening",
    audioText: "无论遇到什么困难，他都不放弃",
    question: "Какова главная черта этого человека?",
    options: [
      "он быстро сдаётся",
      "он никогда не сдаётся, какие бы трудности ни были",
      "он избегает трудностей",
      "он часто болеет",
    ],
    correct: 1,
  },
];

export const hskTestQuestions: HskTestQuestionBank = {
  1: HSK_1,
  2: HSK_2,
  3: HSK_3,
  4: HSK_4,
};

/** Get a randomized subset for a level + mode. Stable per session via seed. */
export function pickQuestions(
  level: 1 | 2 | 3 | 4,
  count: number,
  seed?: number,
): HskTestQuestion[] {
  const pool = hskTestQuestions[level].slice();
  const random = seed != null ? mulberry32(seed) : Math.random;
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const take = Math.min(count, pool.length);
  return pool.slice(0, take);
}

/** Graded sequence for the "adaptive" mode. Starts at medium difficulty
 *  and steps into harder/easier slots as the test progresses. Not a true
 *  CAT (the next item is fixed at pick-time, not at answer-time), but the
 *  user-facing difficulty curve genuinely varies — and the result is
 *  computed on the same difficulty-weighted score as the other modes. */
export function pickAdaptive(
  level: 1 | 2 | 3 | 4,
  count: number,
  seed?: number,
): HskTestQuestion[] {
  const all = hskTestQuestions[level].slice();
  const random = seed != null ? mulberry32(seed) : Math.random;
  for (let i = all.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [all[i], all[j]] = [all[j], all[i]];
  }

  const easy = all.filter((q) => q.difficulty === 1.0);
  const medium = all.filter((q) => q.difficulty === 1.5);
  const hard = all.filter((q) => q.difficulty === 2.0);

  // Sequence template: warm up at medium, mix in easy, ramp hard towards
  // the back half. Length 15.
  const template: Array<"e" | "m" | "h"> = [
    "m", "m", "e", "m", "h",
    "e", "m", "h", "m", "e",
    "h", "m", "e", "h", "m",
  ];

  const picked: HskTestQuestion[] = [];
  for (let i = 0; i < Math.min(count, template.length); i++) {
    const bucket =
      template[i] === "e" ? easy : template[i] === "h" ? hard : medium;
    const fallback = medium.length ? medium : hard.length ? hard : easy;
    const next = bucket.shift() ?? fallback.shift();
    if (next) picked.push(next);
  }
  return picked;
}

function mulberry32(seed: number) {
  let t = seed >>> 0;
  return function () {
    t = (t + 0x6d2b79f5) >>> 0;
    let r = Math.imul(t ^ (t >>> 15), 1 | t);
    r = (r + Math.imul(r ^ (r >>> 7), 61 | r)) ^ r;
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}
